# Generated by Django 5.2.4 on 2025-07-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_skill_certificate_alter_skill_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='images/skill/certificate/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='profile_image',
            field=models.ImageField(upload_to='images/skill/skill_image/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/skills/'),
        ),
    ]
